"""Compatibility facade for legacy capture-service imports.

The active capture authority now lives under `webview_screenshort.capture.service`.
This module remains only to preserve older import paths while the package
migration settles.
"""

from .capture.runtime import RESPONSIVE_CAPTURE_SET
from .capture.service import (
    AuthContext,
    CaptureResult,
    CaptureSetResult,
    PreloadedStateContext,
    Reporter,
    ScreenshotConfig,
    apply_suffix,
    build_auth_context,
    build_capture_set_witness_index,
    build_evidence_bundle_payload,
    build_fallback_request_headers,
    build_report_payload,
    build_semantic_page_summary,
    capture_fallback,
    capture_from_args,
    capture_primary,
    collect_html_witnesses,
    default_output_dir,
    derive_neighbor_path,
    emit_capture_set_text,
    emit_result,
    emit_single_capture_text,
    ensure_image_suffix,
    ensure_json_suffix,
    ensure_parent_dir,
    execute_capture,
    extract_title_from_html,
    finalize_capture_artifacts,
    generate_bundle_path,
    generate_output_path,
    generate_report_path,
    html_to_text,
    load_config,
    load_plugin_version,
    normalize_url,
    normalize_witness_mode,
    read_png_dimensions,
    redact_auth_context,
    response_summary,
    run_capture,
    run_responsive_capture_set,
    validate_png,
    write_capture_set_witness_file,
    write_evidence_bundle_file,
    write_json_file,
    write_report_file,
    write_text_file,
)

__all__ = [
    "AuthContext",
    "CaptureResult",
    "CaptureSetResult",
    "PreloadedStateContext",
    "RESPONSIVE_CAPTURE_SET",
    "Reporter",
    "ScreenshotConfig",
    "apply_suffix",
    "build_auth_context",
    "build_capture_set_witness_index",
    "build_evidence_bundle_payload",
    "build_fallback_request_headers",
    "build_report_payload",
    "build_semantic_page_summary",
    "capture_fallback",
    "capture_from_args",
    "capture_primary",
    "collect_html_witnesses",
    "default_output_dir",
    "derive_neighbor_path",
    "emit_capture_set_text",
    "emit_result",
    "emit_single_capture_text",
    "ensure_image_suffix",
    "ensure_json_suffix",
    "ensure_parent_dir",
    "execute_capture",
    "extract_title_from_html",
    "finalize_capture_artifacts",
    "generate_bundle_path",
    "generate_output_path",
    "generate_report_path",
    "html_to_text",
    "load_config",
    "load_plugin_version",
    "normalize_url",
    "normalize_witness_mode",
    "read_png_dimensions",
    "redact_auth_context",
    "response_summary",
    "run_capture",
    "run_responsive_capture_set",
    "validate_png",
    "write_capture_set_witness_file",
    "write_evidence_bundle_file",
    "write_json_file",
    "write_report_file",
    "write_text_file",
]
